#!/usr/bin/env bash
#
# Reboot by shutting down and power cycling through the Strato Pi MCU.

set -euo pipefail

SYSFS_PATH="/sys/class/stratopimax"

echo "1" >"${SYSFS_PATH}/power/down_enabled"

shutdown now
